language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  # - "pypy"
  - "nightly"
install:
    - if [[ $TRAVIS_PYTHON_VERSION != 3.3 || $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install fabric unittest2; fi
    - pip install awesome-slugify
    - pip install coveralls
    - pip install nose
    - pip install future
    - pip install six
script:
    - python setup.py build
    - python setup.py sdist
    - nosetests -v --with-coverage --cover-package=misc-filename-utils --cover-tests --cover-erase --with-doctest
after_success:
    - coveralls
notifications:
    email: false
