language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
    - pip install awesome-slugify
    - pip install coveralls
    - pip install nose
    - pip install future
    - pip install six
script:
    - python setup.py build
    - python setup.py sdist
    - nosetests -v --with-coverage --cover-package=misc_filename_utils --cover-tests --cover-erase --with-doctest
after_success:
    - coveralls
notifications:
    email: false
